### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [RetnoSuciWulandari/prj-rev-bwfs-dasmoto#2]
Here, there are several properties that are shared among the 3 section headings (ie. `.brush`, `.frame`, `.paint`): https://github.com/RetnoSuciWulandari/prj-rev-bwfs-dasmoto/blob/master/html_css_dasmoto_project/style.css#L7-L24

To avoid repetition in the stylesheet, you could use `h2` as the selector to specify the shared properties for all 3 headings at once:
```css
h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
